/** Sync actions **/

export const COMPLETE_TASK = 'COMPLETE_TASK';
export const CREATE_TASK = 'CREATE_TASK';

/** Async actions **/

/** TASK **/
export const LOAD_TASKS_FAILURE = 'LOAD_TASKS_FAILURE';
export const LOAD_TASKS_SUCCESS = 'LOAD_TASKS_SUCCESS';

export const UPDATE_TASKS_FAILURE = 'UPDATE_TASKS_FAILURE';
export const UPDATE_TASKS_SUCCESS = 'UPDATE_TASKS_SUCCESS';

/** TAG **/
export const LOAD_TAGS_FAILURE = 'LOAD_TAGS_FAILURE';
export const LOAD_TAGS_SUCCESS = 'LOAD_TAGS_SUCCESS';

export const UPDATE_TAGS_FAILURE = 'UPDATE_TAGS_FAILURE';
export const UPDATE_TAGS_SUCCESS = 'UPDATE_TAGS_SUCCESS';
