export const LOAD_TASKS_FAILURE = 'LOAD_TASKS_FAILURE';
export const LOAD_TASKS_SUCCESS = 'LOAD_TASKS_SUCCESS';
export const COMPLETE_TASK = 'COMPLETE_TASK';
export const CREATE_TASK = 'CREATE_TASK';
